{
 "title": "UTAC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Chemical Tin Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "request_prediction_ct3hours{}", "legendFormat": "3 hours ahead" },
    { "expr": "request_prediction_ct24hours{}", "legendFormat": "24 hours ahead" },
    {
     "expr": "request_prediction_ct168hours{}",
     "legendFormat": "168 hours ahead"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_latency_seconds{endpoint=~\"/predict/ct/hours168|/predict/ct/hours24|/predict/ct/hours3|/predict/st/hours168|/predict/st/hours24|/predict/st/hours3\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Solder Thickness Prediction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "request_prediction_st3hours{}", "legendFormat": "3 hours ahead" },
    { "expr": "request_prediction_st24hours{}", "legendFormat": "24 hours ahead" },
    {
     "expr": "request_prediction_st168hours{}",
     "legendFormat": "168 hours ahead"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{endpoint=~\"/predict/ct/hours168|/predict/ct/hours24|/predict/ct/hours3|/predict/st/hours168|/predict/st/hours24|/predict/st/hours3\"}",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Model Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_version_ct3hours{}", "legendFormat": "ct3hours" },
    { "expr": "model_version_ct24hours{}", "legendFormat": "ct24hours" },
    { "expr": "model_version_ct168hours{}", "legendFormat": "ct168hours" },
    { "expr": "model_version_st3hours{}", "legendFormat": "st3hours" },
    { "expr": "model_version_st24hours{}", "legendFormat": "st24hours" },
    { "expr": "model_version_st168hours{}", "legendFormat": "st168hours" }
   ]
  },
  {
   "title": "Model Retrain Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "model_retrain_ct3hours_total{}", "legendFormat": "ct3hours" },
    {
     "expr": "model_retrain_ct24hours_total{}",
     "legendFormat": "ct24hours"
    },
    {
     "expr": "model_retrain_ct168hours_total{}",
     "legendFormat": "ct168hours"
    },
    { "expr": "model_retrain_st3hours_total{}", "legendFormat": "st3hours" },
    {
     "expr": "model_retrain_st24hours_total{}",
     "legendFormat": "st24hours"
    },
    {
     "expr": "model_retrain_st168hours_total{}",
     "legendFormat": "st168hours"
    }
   ]
  },
  {
   "title": "Model Retraining Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "model_status_ct3hours{model_status_ct3hours=\"retraining\"}",
     "legendFormat": "ct3hours"
    },
    {
     "expr": "model_status_ct24hours{model_status_ct24hours=\"retraining\"}",
     "legendFormat": "ct24hours"
    },
    {
     "expr": "model_status_ct168hours{model_status_ct168hours=\"retraining\"}",
     "legendFormat": "ct168hours"
    },
    {
     "expr": "model_status_st3hours{model_status_st3hours=\"retraining\"}",
     "legendFormat": "st3hours"
    },
    {
     "expr": "model_status_st24hours{model_status_st24hours=\"retraining\"}",
     "legendFormat": "st24hours"
    },
    {
     "expr": "model_status_st168hours{model_status_st168hours=\"retraining\"}",
     "legendFormat": "st168hours"
    }
   ]
  }
 ]
}